require("data-tweaks.multiply-recipes")
require("data-tweaks.remove-long-inserters")
require("data-tweaks.multiply-splitter-speeds")
require("data-tweaks.multiply-belt-speeds")
require("data-tweaks.multiply-inserter-speeds")